# code: language=python
# pyinstaller.spec
# This file tells PyInstaller how to bundle the monorepo application with dynamic plugin discovery
from PyInstaller.utils.hooks import copy_metadata
from PyInstaller.building.api import EXE, PYZ
from PyInstaller.building.build_main import Analysis
import sys
import os
import site
from pathlib import Path

# Import plugin discovery system
try:
    import importlib.metadata as importlib_metadata
except ImportError:
    import importlib_metadata


# ============================================================================
# Plugin Discovery System
# ============================================================================

def discover_plugins():
    """
    Discover all installed plugins via entry points.

    Returns:
        dict: Dictionary with 'analyzers' and 'tokenizers' keys containing
              lists of plugin metadata (name, module, attr).
    """
    plugins = {
        'analyzers': [],
        'tokenizers': []
    }

    print("=" * 70)
    print("DISCOVERING PLUGINS FOR PYINSTALLER BUILD")
    print("=" * 70)

    # Discover analyzer plugins
    try:
        eps = importlib_metadata.entry_points()
        # Handle both old (dict) and new (SelectableGroups) API
        if hasattr(eps, 'select'):
            analyzer_eps = eps.select(group='cibmangotree.analyzers')
        else:
            analyzer_eps = eps.get('cibmangotree.analyzers', [])

        for ep in analyzer_eps:
            module_path = ep.value.split(':')[0]
            attr_name = ep.value.split(':')[1] if ':' in ep.value else None
            plugins['analyzers'].append({
                'name': ep.name,
                'module': module_path,
                'attr': attr_name
            })
            print(f"  [Analyzer] {ep.name:20s} -> {module_path}")
    except Exception as e:
        print(f"  Warning: Could not discover analyzer plugins: {e}")

    # Discover tokenizer plugins
    try:
        eps = importlib_metadata.entry_points()
        if hasattr(eps, 'select'):
            tokenizer_eps = eps.select(group='cibmangotree.tokenizers')
        else:
            tokenizer_eps = eps.get('cibmangotree.tokenizers', [])

        for ep in tokenizer_eps:
            module_path = ep.value.split(':')[0]
            attr_name = ep.value.split(':')[1] if ':' in ep.value else None
            plugins['tokenizers'].append({
                'name': ep.name,
                'module': module_path,
                'attr': attr_name
            })
            print(f"  [Tokenizer] {ep.name:20s} -> {module_path}")
    except Exception as e:
        print(f"  Warning: Could not discover tokenizer plugins: {e}")

    print(f"\nTotal discovered: {len(plugins['analyzers'])} analyzers, "
          f"{len(plugins['tokenizers'])} tokenizers")
    print("=" * 70)

    return plugins


def generate_frozen_plugins(plugins):
    """
    Generate frozen plugins file for PyInstaller.

    This file provides explicit imports for all plugins that would normally
    be discovered via entry points (which don't work in frozen executables).

    Args:
        plugins: Dictionary from discover_plugins()

    Returns:
        str: Path to the generated frozen plugins file
    """
    frozen_file = Path('packages/core/src/cibmangotree/_frozen_plugins.py')

    content = '''"""
Auto-generated frozen plugins for PyInstaller builds.
DO NOT EDIT - Generated by pyinstaller.spec

This file is used when the application is frozen (packaged with PyInstaller)
to provide explicit plugin imports, since entry points don't work in frozen apps.
"""

# Analyzer plugins - mapping from plugin name to module path
ANALYZER_PLUGINS = {
'''

    for plugin in plugins['analyzers']:
        content += f"    '{plugin['name']}': '{plugin['module']}:{plugin['attr']}',\n"

    content += '''}\n
# Tokenizer plugins - mapping from plugin name to module path
TOKENIZER_PLUGINS = {
'''

    for plugin in plugins['tokenizers']:
        content += f"    '{plugin['name']}': '{plugin['module']}:{plugin['attr']}',\n"

    content += '''}\n
def is_frozen():
    """Check if running in a frozen (PyInstaller) environment."""
    return getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS')
'''

    # Ensure directory exists
    frozen_file.parent.mkdir(parents=True, exist_ok=True)
    frozen_file.write_text(content)

    print(f"\nGenerated frozen plugins file: {frozen_file}")
    return str(frozen_file)


def get_plugin_hiddenimports(plugins):
    """
    Get all plugin modules for PyInstaller's hiddenimports.

    Args:
        plugins: Dictionary from discover_plugins()

    Returns:
        list: List of module paths to include as hidden imports
    """
    imports = []

    # Add analyzer modules
    for plugin in plugins['analyzers']:
        base_module = plugin['module'].split('.')[0]
        imports.append(plugin['module'])
        imports.append(base_module)

    # Add tokenizer modules
    for plugin in plugins['tokenizers']:
        base_module = plugin['module'].split('.')[0]
        imports.append(plugin['module'])
        imports.append(base_module)

    # Remove duplicates while preserving order
    seen = set()
    unique_imports = []
    for imp in imports:
        if imp not in seen:
            seen.add(imp)
            unique_imports.append(imp)

    return unique_imports


# ============================================================================
# Site Packages Detection
# ============================================================================

site_packages_path = None
block_cipher = None

for site_path in site.getsitepackages():
    if 'site-packages' in site_path:
        site_packages_path = site_path
        break

if site_packages_path is None:
    raise RuntimeError(
        "The site-packages directory could not be found. "
        "Please setup the python environment correctly and try again..."
    )

print(f"\nUsing site-packages: {site_packages_path}\n")


# ============================================================================
# Plugin Discovery and Frozen Plugin Generation
# ============================================================================

# Discover all plugins via entry points
discovered_plugins = discover_plugins()

# Generate frozen plugins file for runtime
frozen_plugins_file = generate_frozen_plugins(discovered_plugins)

# Get all plugin modules for hiddenimports
plugin_imports = get_plugin_hiddenimports(discovered_plugins)


# ============================================================================
# PyInstaller Analysis Configuration
# ============================================================================

a = Analysis(
    ['cibmangotree.py'],  # Entry point (imports from cibmangotree package)
    pathex=[
        'packages/core/src',  # Core package source
    ],
    binaries=[],
    datas=[
        # Version file, if defined
        *(
            [('./VERSION', '.')]
            if os.path.exists('VERSION') else []
        ),

        # Inquirer depends on readchar as a hidden dependency that requires package metadata
        *copy_metadata('readchar'),

        # Static assets for web servers (from site-packages)
        (os.path.join(site_packages_path, 'shiny/www'), 'shiny/www'),
        (os.path.join(site_packages_path, 'shinywidgets/static'), 'shinywidgets/static'),

        # Application static assets (from monorepo)
        ('packages/core/src/cibmangotree/app/web_static', 'cibmangotree/app/web_static'),
        ('packages/core/src/cibmangotree/app/web_templates', 'cibmangotree/app/web_templates'),

        # Include the frozen plugins file
        (frozen_plugins_file, 'cibmangotree'),
    ],
    hiddenimports=[
        # Core package modules
        'cibmangotree',
        'cibmangotree.__main__',
        'cibmangotree.app',
        'cibmangotree.analyzer_interface',
        'cibmangotree.tui',
        'cibmangotree.tui.components',
        'cibmangotree.tui.tools',
        'cibmangotree.services',
        'cibmangotree.services.storage',
        'cibmangotree.services.data_import',
        'cibmangotree.services.tokenizers',
        'cibmangotree.context',
        'cibmangotree.meta',
        'cibmangotree.plugin_system',
        'cibmangotree.plugin_system.analyzer_loader',
        'cibmangotree.plugin_system.tokenizer_loader',

        # Dynamically discovered plugin modules
        *plugin_imports,

        # Terminal UI dependencies
        'readchar',
        'inquirer',
        'rich',
        'colorama',

        # Data processing
        'numpy',
        'numpy.core.multiarray',
        'polars',
        'pandas',
        'pyarrow',

        # Visualization
        'plotly',
        'plotly.graph_objs',

        # Web frameworks
        'dash',
        'dash.dependencies',
        'shiny',
        'shiny.ui',
        'shiny.server',
        'shinywidgets',
        'htmltools',
        'starlette',
        'starlette.middleware',
        'starlette.routing',

        # Web server
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'asyncio',
        'websockets',
        'websockets.legacy',
        'websockets.legacy.server',

        # Markdown rendering (for Shiny)
        'linkify_it',
        'markdown_it',
        'mdit_py_plugins',
        'mdurl',
        'uc_micro',

        # Logging
        'pythonjsonlogger',
        'pythonjsonlogger.jsonlogger',

        # Storage
        'tinydb',
        'platformdirs',
        'filelock',

        # Text processing
        'regex',

        # Data validation
        'pydantic',
        'pydantic.v1',

        # Import/Export
        'xlsxwriter',
        'fastexcel',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
)

# ============================================================================
# Build Configuration
# ============================================================================

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

if sys.platform == "darwin":
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        name='cibmangotree',  # The name of the executable
        debug=False,
        strip=True,
        upx=True,
        console=True,
        entitlements_file="./mango.entitlements",
        codesign_identity=os.getenv('APPLE_APP_CERT_ID'),
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        name='cibmangotree',
        debug=False,
        strip=False,
        upx=True,
        console=True,
    )
